### ISSUE TITLE
AttributeError occurs when running orjson.dumps with orjson 3.10.0

### ISSUE THREAD

**Issue by sonyakun** [ijl/orjson#467]
AttributeError occurs only when running `orjson.dumps` with orjson 3.10.0. (Others have not been done yet) It works fine in versions before 3.10.0.

**Comment by sbrunato** [comment]
*Similar* error on our side, our tests in CI are failing with `orjson 3.10.0` on `windows + python 3.12` (no problem on linux or windows+python 3.8):
```
E       AttributeError: module 'orjson' has no attribute 'loads'
```
