### ISSUE TITLE
Publish PEP 517 sdist

### ISSUE THREAD

**Issue by ijl** [ijl/orjson#8]
Needs https://github.com/PyO3/pyo3-pack/issues/2.

**Comment by gatopeich** [comment]
Meanwhile, is there any other way to build orjson on alpine Linux?

**Comment by ijl** [comment]
You can try the instructions in https://github.com/ijl/orjson#install. Building a pyo3 project against Python using musl libc may not succeed right now, I don't know.

**Comment by bsergean** [comment]
I would love to use orjson as well, but I like my small alpine containers. 

Sounds like pyo3 is the project that would know about musl / alpine linux things.

**Comment by bsergean** [comment]
The pyo3 project says to use `--manylinux` when building.

(your instructions do not mention this flag)
```
git clone https://github.com/ijl/orjson.git && cd orjson
pip install --upgrade pyo3-pack
pyo3-pack build --release --strip --interpreter python3.7
```

I'll give it a try to see if this can be built from scratch on Alpine.

**Comment by ijl** [comment]
2.0.7 includes an sdist using pyo3-pack. 

@konstin, thank you for adding that to pyo3-pack.

**Comment by bsergean** [comment]
I should probably create a different github issue, but here's my failed attempt at installing 2.0.7 on Alpine (in docker). I tried with and without the --user flag, as root and as a normal user. I have (latest ?) pip (19.2.3).

```Step 15/18 : RUN pip install orjson==2.0.7 --user
 ---> Running in f6955bd4d145
Collecting orjson==2.0.7
  Downloading https://files.pythonhosted.org/packages/8c/9a/f1d72af21340fae73b5ae0d75f015ee7caf27c808e0fae3659d2246ff1e7/orjson-2.0.7.tar.gz (480kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: /usr/local/bin/python /usr/local/lib/python3.7/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-99ysc57q/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'pyo3-pack>=0.7.0.beta11,<0.8'
       cwd: None
  Complete output (33 lines):
  Collecting pyo3-pack<0.8,>=0.7.0.beta11
    Downloading https://files.pythonhosted.org/packages/15/90/9c0ae42b8c9bfcad8a897353185f64ba47064d898e99b89957695858251f/pyo3_pack-0.7.0_beta.11.tar.gz (78kB)
    Installing build dependencies: started
    Installing build dependencies: finished with status 'error'
    ERROR: Command errored out with exit status 2:
     command: /usr/local/bin/python /usr/local/lib/python3.7/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-hc8y5lnr/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- pyo3-pack
         cwd: None
    Complete output (23 lines):
    Collecting pyo3-pack
      Using cached https://files.pythonhosted.org/packages/15/90/9c0ae42b8c9bfcad8a897353185f64ba47064d898e99b89957695858251f/pyo3_pack-0.7.0_beta.11.tar.gz
    ERROR: Exception:
    Traceback (most recent call last):
      File "/usr/local/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 188, in main
        status = self.run(options, args)
      File "/usr/local/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 345, in run
        resolver.resolve(requirement_set)
      File "/usr/local/lib/python3.7/site-packages/pip/_internal/legacy_resolve.py", line 196, in resolve
        self._resolve_one(requirement_set, req)
      File "/usr/local/lib/python3.7/site-packages/pip/_internal/legacy_resolve.py", line 359, in _resolve_one
        abstract_dist = self._get_abstract_dist_for(req_to_install)
      File "/usr/local/lib/python3.7/site-packages/pip/_internal/legacy_resolve.py", line 307, in _get_abstract_dist_for
        self.require_hashes
      File "/usr/local/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 213, in prepare_linked_requirement
        with self.req_tracker.track(req):
      File "/usr/local/lib/python3.7/contextlib.py", line 112, in __enter__
        return next(self.gen)
      File "/usr/local/lib/python3.7/site-packages/pip/_internal/req/req_tracker.py", line 94, in track
        self.add(req)
      File "/usr/local/lib/python3.7/site-packages/pip/_internal/req/req_tracker.py", line 63, in add
        % (link, fp.read()))
    LookupError: https://files.pythonhosted.org/packages/15/90/9c0ae42b8c9bfcad8a897353185f64ba47064d898e99b89957695858251f/pyo3_pack-0.7.0_beta.11.tar.gz#sha256=93bf2789bb5e27c57af4b9b9b03f48ed84ff99c62852626c9ac51036845df6d3 (from https://pypi.org/simple/pyo3-pack/) is already being built: pyo3-pack<0.8,>=0.7.0.beta11 from https://files.pythonhosted.org/packages/15/90/9c0ae42b8c9bfcad8a897353185f64ba47064d898e99b89957695858251f/pyo3_pack-0.7.0_beta.11.tar.gz#sha256=93bf2789bb5e27c57af4b9b9b03f48ed84ff99c62852626c9ac51036845df6d3
    ----------------------------------------
  ERROR: Command errored out with exit status 2: /usr/local/bin/python /usr/local/lib/python3.7/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-hc8y5lnr/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- pyo3-pack Check the logs for full command output.
  ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/local/bin/python /usr/local/lib/python3.7/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-99ysc57q/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'pyo3-pack>=0.7.0.beta11,<0.8' Check the logs for full command output.
The command '/bin/sh -c pip install orjson==2.0.7 --user' returned a non-zero code: 1
```

**Comment by ijl** [comment]
musl libc isn't supported.

**Comment by bsergean** [comment]
Got it. Thanks.

**Comment by bsergean** [comment]
FYI I just learned about the bitnami docker images which are glibc based, but very small like Alpine.

**Comment by gatopeich** [comment]
I managed to get it working on Alpine Linux by hacking the dist into believing it is "manylinux" with a couple lines.
Will share it later...

**Comment by gatopeich** [comment]
Here is my Docker recipe to have orjson on Alpine Linux:
```
FROM python:3.7-alpine
RUN echo 'manylinux1_compatible = True' > /usr/local/lib/python3.7/_manylinux.py
RUN pip3 install orjson
RUN rm /usr/local/lib/python3.7/_manylinux.py
```
And yes it works.

**Comment by bsergean** [comment]
Thanks for sharing, I might give it a try.

**Comment by goodking-bq** [comment]
> Here is my Docker recipe to have orjson on Alpine Linux:
> 
> ```
> FROM python:3.7-alpine
> RUN echo 'manylinux1_compatible = True' > /usr/local/lib/python3.7/_manylinux.py
> RUN pip3 install orjson
> RUN rm /usr/local/lib/python3.7/_manylinux.py
> ```
> 
> And yes it works.

i had try this,success install ,,but import raise error 

```
/ # python -c "import orjson"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: Error relocating /usr/local/lib/python3.7/site-packages/orjson.cpython-37m-x86_64-linux-gnu.so: __register_atfork: symbol not found
```

have any idear?

**Comment by gatopeich** [comment]
> ImportError: Error relocating /usr/local/lib/python3.7/site-packages/orjson.cpython-37m-x86_64-linux-gnu.so: __register_atfork: symbol not found

This annoying symbol dependency was added in v2.0.10.
My current solution is to install orjson==2.0.9

**Comment by scuml** [comment]
Got the latest orjson working on on alpine3.11

Dockerfile
`
FROM python:3.8.1-alpine3.11 as base

# Install rustup to get nightly build
RUN wget -O init.sh https://sh.rustup.rs
RUN sh init.sh -y
RUN cp $HOME/.cargo/bin/* /usr/local/bin

RUN rustup install nightly
RUN rustup default nightly

# use static linking to allow rust to compile orjson
ENV RUSTFLAGS "-C target-feature=-crt-static"
`

**Comment by gatopeich** [comment]
> Got the latest orjson working on on alpine3.11
> ...
> ENV RUSTFLAGS "-C target-feature=-crt-static"

How does this install orjson?

**Comment by scuml** [comment]
> How does this install orjson?

This allows one to install a python requirements file that includes the latest orjson.  Without these lines, one will run into a compilation error.  I've added `RUN pip install orjson` to the end to help clarify.

**Comment by ashleysommer** [comment]
An update for anyone coming to this issue looking to run newest orjson on Alpine.
I've worked out how to do it on vanilla alpine without installing glibc and without using the rust toolchain. (I'm using alpine 3.9 and python 3.6 but should work with newer versions).
Its based on the comment by @gatopeich above: https://github.com/ijl/orjson/issues/8#issuecomment-526621349
The key is that orjson `v2.5.1` now builds `manylinux1`-compatible wheels.
Also required is `gcompat` (a true manylinux1-compatible build shouldn't require gcompat, but alas this seems to still need it)
Here's my alpine recipe:
```
FROM alpine:3.9
RUN echo "https://dl-3.alpinelinux.org/alpine/v3.9/main" >> /etc/apk/repositories
RUN echo "https://dl-3.alpinelinux.org/alpine/v3.9/community" >> /etc/apk/repositories
RUN apk add --no-cache python3 gcompat patchelf
RUN patchelf --add-needed libgcompat.so.0 /usr/bin/python3.6
RUN echo 'manylinux1_compatible = True' > /usr/lib/python3.6/_manylinux.py &&\
    pip3 install "orjson>=2.5.1" &&\
    rm /usr/lib/python3.6/_manylinux.py
```
I have this r

**Comment by ashleysommer** [comment]
Tested, the above recipe also works on Alpine 3.10, with Python 3.7 using the following recipe, but it _doesn't_ work on Alpine 3.11, with Ptyhon 3.8.
```
FROM alpine:3.10
RUN echo "https://dl-3.alpinelinux.org/alpine/v3.10/main" >> /etc/apk/repositories
RUN echo "https://dl-3.alpinelinux.org/alpine/v3.10/community" >> /etc/apk/repositories
RUN apk add --no-cache python3 gcompat patchelf
RUN patchelf --add-needed libgcompat.so.0 /usr/bin/python3.7
RUN echo 'manylinux1_compatible = True' > /usr/lib/python3.7/_manylinux.py &&\
    pip3 install "orjson>=2.5.1" &&\
    rm /usr/lib/python3.7/_manylinux.py
```

**Comment by gatopeich** [comment]
Somehow 'gcompat' worked with ipython on alpine:3.11:
```
$ docker exec -it e6c2f76e71f2 sh                  
/ # ipython
Python 3.8.2 (default, Feb 29 2020, 17:03:31)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.10.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import orjson

In [2]: orjson.loads('{"a":1}')
Out[2]: {'a': 1}

In [3]:
Do you really want to exit ([y]/n)?
/ # history
   0 cat /etc/issue
   1 bash
   2 apk add py3-pip
   3 pip
   4 pip3
   5 pip3 version
   6 pip3 -V
   7 python
   8 python3
   9 pip3 install orjson
  10 apk add --no-cache python3 gcompat patchelf
  11 echo 'manylinux1_compatible = True' > /usr/lib/python3.8/_manylinux.py
  12 pip3 install "orjson>=2.5.1"
  13 rm /usr/lib/python3.8/_manylinux.py
  14 apk add ipython
  15 ipython
  16 history
/ # cat /etc/issue
Welcome to Alpine Linux 3.11
```

**Comment by ashleysommer** [comment]
That's great news. Perhaps it's a newer version of gcompat now on alpine 3.11?

**Comment by gatopeich** [comment]
Must be a combination of gcompat and *patchelf* because if I don't install patchelf there is an import error.

**Comment by NotoriousRebel** [comment]
@gatopeich Any chance you know why it doesn't work on python3.8-alpine3.10?

**Comment by gatopeich** [comment]
@NotoriousRebel there was some library symbol missing on 3.10, and no supported way to amend it.

**Comment by ashleysommer** [comment]
I know its been 6 months since I've commented here, but revisiting this now for a different project I'm working on, and I've investigated the issue with Python 3.8 and Alpine 3.11 a bit more.
The reason it worked for @gatopeich in April, but did not work for me in March, is not due to a different gcompat or patchelf version. But actually due to a newer _orjson_ version. I was using orjson version 2.5.1 (the first with proper manylinux1 compatibility) but @gatopeich in April used the newer orjosn v2.6.5. Theres some reason due to a combination of using Python 3.8 and orjson 2.6.5, that means the python3 binary does _not_ need to be patched using patchelf.
`gcompat` still needs to be installed, because orjson import `ld-linux-x86_64.so.2` that is provided by `gcompat`.

However, in the last 6 months there has been a _lot_ of changes in orjson, particularly in relation to building and publishing. Eg, manylinux1 builds are no longer published since 3.4.0, so we need to use v3.3.1 or older. Also, orjson v2.6.5 and above requires `libgcc_s.so.1` that is provided by libgcc. That is why it worked for @gatopeich when they installed `patchelf`. Even though patchelf isn't used, it depends on `libgcc` which brings in that library.

So here is a basic docker recipe for using orjson in alpine v3.11 with Python 3.8
```
FROM alpine:3.11
RUN echo "https://dl-3.alpinelinux.org/alpine/v3.11/main" >> /etc/apk/repositories
RUN echo "https://dl-3.alpinelinux.org/alpine/v3.11/community" >> /etc/apk/repositories
RUN apk add --no-cache python3 gcompat libgcc
RUN echo 'manylinux1_compatible = True' > /usr/lib/python3.8/_manylinux.py &&\
    pip3 install "orjson>=2.6.5,<3.4.0" &&\
    rm /usr/lib/python3.8/_manylinux.py
RUN python3 -c "import orjson; print(orjson.dumps(list(range(10))))"
```

**Comment by ashleysommer** [comment]
And finally, I just did a build on Alpine 3.12 with Python 3.8.5. Theres not much different here, except we need to install py3-pip to use `pip3`. In this case we can now use the manylinux2014 builds, so we can use orjson v3.3.1 up to the current version.

```
FROM alpine:3.12
RUN echo "https://dl-3.alpinelinux.org/alpine/v3.12/main" >> /etc/apk/repositories
RUN echo "https://dl-3.alpinelinux.org/alpine/v3.12/community" >> /etc/apk/repositories
RUN apk add --no-cache python3 py3-pip gcompat libgcc
RUN echo 'manylinux2014_compatible = True' > /usr/lib/python3.8/_manylinux.py &&\
    pip3 install "orjson>=3.3.1" &&\
    rm /usr/lib/python3.8/_manylinux.py
RUN python3 --version
RUN python3 -c "import orjson; print(orjson.dumps(list(range(10))))"
```

**Comment by aspin** [comment]
The above solution doesn't seem to work for the latest version of pip. For now, I've pinned `pip==20.2.2` when trying to install `orjson`. Not really sure what's changed in the latest `pip` (`20.3.3` as of writing), but on my image it doesn't seem to even get to the check for the `_manylinux.py` file, seemingly because `pip` isn't able to find glibc in the system

**Comment by gatopeich** [comment]
> And finally, I just did a build on Alpine 3.12 with Python 3.8.5.

Thanks, @ashleysommer, that works like a charm even today with Python 3.8.8:
```
$ docker run -it alpine:3.12                                                                                                   
/ # echo "https://dl-3.alpinelinux.org/alpine/v3.12/main" >> /etc/apk/repositories                                                                           
/ # echo "https://dl-3.alpinelinux.org/alpine/v3.12/community" >> /etc/apk/repositories                                                                      
/ # apk add --no-cache python3 py3-pip gcompat libgcc                                                                                                        
...
(40/40) Installing py3-pip (20.1.1-r0)
...
/ # echo 'manylinux2014_compatible = True' > /usr/lib/python3.8/_manylinux.py
/ # pip3 install "orjson>=3.3.1"
Collecting orjson>=3.3.1
  Downloading orjson-3.5.1-cp38-cp38-manylinux2014_x86_64.whl (233 kB)
     |████████████████████████████████| 233 kB 2.6 MB/s
Installing collected packages: orjson
Successfully installed orjson-3.5.1
/ # rm /usr/lib/python3.8/_manylinux.py
/ # python3 --version
Python 3.8.8
/ # python3 -c "import orjson; print(orjson.dumps(list(range(10))))"
b'[0,1,2,3,4,5,6,7,8,9]'
```

@aspin, I can only guess you were not using the bundled `py3-pip` for your own reasons.

**Comment by AngryUbuntuNerd** [comment]
I came up with a solution combining a few of the above mentioned:

```Dockerfile
FROM python:3.6-alpine

RUN echo 'manylinux2014_compatible = True' > /usr/local/lib/python3.6/_manylinux.py && \
    apk add --no-cache gcompat libgcc && \
    pip install "pip==20.2.2" --user && \
    pip install "orjson~=3.5.1" && \
    pip uninstall -y pip && \
    rm /usr/local/lib/python3.6/_manylinux.py

...  # Install everything else (pip is back to the image version)
```
